export default [
  {word: "Equity", hint: "Ownership share in a company"},
  {word: "Bond", hint: "A debt instrument issued by a company or government"},
  {word: "IPO", hint: "Initial Public Offering  company goes public"},
  {word: "Dividend", hint: "Profit distribution to shareholders"},
  {word: "Liquidity", hint: "Ease of converting assets into cash"},
  {word: "Portfolio", hint: "Collection of investments held by an investor"},
  {word: "Mutual Fund", hint: "Pooled investment managed by professionals"},
  {word: "Index", hint: "A statistical measure of market performance"},
  {word: "Capital Gain", hint: "Profit from selling an asset at higher price"},
  {word: "Bear Market", hint: "Market trend where prices fall"},
  {word: "Bull Market", hint: "Market trend where prices rise"},
  {word: "Blue Chip", hint: "Large, well-established, financially sound company"},
  {word: "Derivative", hint: "Financial contract deriving value from underlying asset"},
  {word: "ETF", hint: "Exchange-Traded Fund trades like stock, represents basket of assets"},
  {word: "Yield", hint: "Income return on investment, often as a percentage"},
  {word: "Volatility", hint: "Degree of variation in asset prices"},
  {word: "Market Cap", hint: "Total value of a company's outstanding shares"},
  {word: "Futures", hint: "Contract to buy/sell an asset at a future date"},
  {word: "Option", hint: "Contract giving right, not obligation, to buy/sell asset"},
  {word: "Securities", hint: "Tradable financial instruments like stocks or bonds"},
  {word: "Liquidity Ratio", hint: "Measures a firm's ability to meet short-term obligations"},
  {word: "Debenture", hint: "A type of long-term debt instrument"},
  {word: "Sector", hint: "A group of companies in similar industries"},
  {word: "Broker", hint: "Intermediary facilitating buying and selling of securities"},
  {word: "Speculation", hint: "Taking high-risk positions hoping for high returns"},
  {word: "Asset", hint: "Resource with economic value owned by individual or company"},
  {word: "Liability", hint: "Financial obligation or debt"},
  {word: "Equity Market", hint: "Market for trading company shares"},
  {word: "Debt Market", hint: "Market for trading bonds and other debt instruments"},
  {word: "Capital", hint: "Financial assets or resources available for investment"},
  {word: "Risk", hint: "Possibility of financial loss in investment"},
];
