export default [
  {word: "Accrued Interest", hint: "Interest accumulated on a bond or loan since the last payment"},
  {word: "After-Market", hint: "Trading of securities that occurs after regular market hours"},
  {word: "Allocation", hint: "Distribution of shares among investors during an IPO"},
  {word: "Amortization", hint: "Gradual repayment of debt or spreading of an asset's cost over time"},
  {word: "Annual Report", hint: "A yearly summary of a company’s financial performance"},
  {word: "Arbitrage", hint: "Buying and selling the same asset in different markets for profit"},
  {word: "Ask Price", hint: "Lowest price a seller is willing to accept for a security"},
  {word: "Asset", hint: "Anything of value owned by a company or investor"},
  {word: "Asset Allocation", hint: "Dividing investments among asset types to manage risk"},
  {word: "Authorized Shares", hint: "Maximum number of shares a company can issue"},
  {word: "Balance Sheet", hint: "Financial statement showing assets, liabilities, and equity at a date"},
  {word: "Bear Market", hint: "Market period when stock prices are falling"},
  {word: "Benchmark", hint: "Standard used to measure investment performance"},
  {word: "Beta", hint: "Measure of a stock’s volatility compared to the market"},
  {word: "Bid Price", hint: "Highest price a buyer is willing to pay for a security"},
  {word: "Blue Chip", hint: "Shares of large, financially stable companies"},
  {word: "Bond", hint: "Fixed-income security representing a loan to a borrower"},
  {word: "Book Building", hint: "Process of determining IPO share prices based on investor demand"},
  {word: "Book Value", hint: "Value of company assets minus its liabilities"},
  {word: "Broker", hint: "Licensed individual or firm executing trades for investors"},
  {word: "Bull Market", hint: "Market where stock prices are rising and optimism prevails"},
  {word: "Buyback", hint: "When a company repurchases its own shares"},
  {word: "Capital", hint: "Financial assets or resources available for investment"},
  {word: "Call Option", hint: "Right to buy a security at a set price before expiry"},
  {word: "Capital Gain", hint: "Profit from selling a security at a higher price"},
  {word: "Capital Loss", hint: "Loss from selling a security for less than its cost"},
  {word: "Capital Market", hint: "Market for long-term securities like stocks and bonds"},
  {word: "Clearing House", hint: "Institution ensuring trade settlement between parties"},
  {word: "Closing Price", hint: "Last trading price of a security at day’s end"},
  {word: "Collateral", hint: "Asset pledged to secure a loan"},
  {word: "Commission", hint: "Fee paid to a broker for executing a trade"},
  {word: "Common Stock", hint: "Share representing ownership and voting rights in a company"},
  {word: "Convertible Bond", hint: "Bond that can be exchanged for company shares"},
  {word: "Corporate Governance", hint: "System of rules guiding company management and control"},
  {word: "Coupon Rate", hint: "Interest rate paid on a bond periodically"},
  {word: "Credit Rating", hint: "Evaluation of a company’s ability to repay debt"},
  {word: "Cross Listing", hint: "When a company lists its shares on multiple exchanges"},
  {word: "Custodian", hint: "Institution that safely holds investors’ securities"},
  {word: "Day Trading", hint: "Buying and selling securities within the same day"},
  {word: "Debenture", hint: "Unsecured long-term debt instrument"},
  {word: "Debt Instrument", hint: "Financial asset representing borrowed funds to be repaid"},
  {word: "Default", hint: "Failure to meet debt repayment or financial obligation"},
  {word: "Derivative", hint: "Financial contract whose value depends on another asset"},
  {word: "Depository", hint: "Institution that holds securities electronically for investors"},
  {word: "Depreciation", hint: "Decrease in asset value over time"},
  {word: "Disclosure", hint: "Providing important company information to investors"},
  {word: "Diversification", hint: "Investing in varied assets to reduce risk"},
  {word: "Dividend", hint: "Portion of company profits paid to shareholders"},
  {word: "Dividend Yield", hint: "Dividend amount as a percentage of share price"},
  {word: "Due Diligence", hint: "Detailed investigation before investing or acquiring"},
  {word: "Dual Listing", hint: "Listing of company shares on two stock exchanges"},


  // newly added words

  { word: "Equity", hint: "Ownership shares in a company listed on an exchange." },
  { word: "ETF", hint: "Exchange-Traded Fund trades like stock, represents basket of assets"},
  { word: "Equity Market", hint: "Market for trading company shares"},
  { word: "Emerging Market", hint: "A developing country’s stock or bond market, still growing/integrating." },
  { word: "Enterprise Value", hint: "The total value of a business including debt and equity (often used in valuations)." },
  { word: "Exposure", hint: "The amount of capital at risk in a particular asset or market." },
  { word: "Efficient Market", hint: "A market where prices fully reflect all available information." },
  { word: "Elasticity", hint: "How market demand reacts to price changes in securities." },
  { word: "Endowment Fund", hint: "A large investment fund (often institutional) that invests across capital markets." },
  { word: "Eurobond", hint: "A bond issued in a currency not native to the country where it is issued." },
  { word: "Futures", hint: "Contract to buy/sell an asset at a future date"},
  { word: "Fixed Income Security", hint: "Debt instrument (like a bond) with regular interest payments." },
  { word: "Futures Contract", hint: "A standardized agreement to buy/sell an asset at a future date and price." },
  { word: "Financial Leverage", hint: "Using borrowed funds to amplify potential returns (and risk)." },
  { word: "Fundamental Analysis", hint: "Method of evaluating securities by analyzing financial statements, market, economy." },
  { word: "Follow‑on Offering", hint: "A subsequent issuance of shares by a company already listed." },
  { word: "Foreign Direct", hint: "Investment into business operations in another country; influences capital flows." },
  { word: "Fallout Risk", hint: "Risk that an issuing firm will be unable to meet its obligations or a deal will collapse." },
  { word: "Flight to Quality", hint: "Movement of capital toward safer securities during market stress." },
  { word: "Floor Trader", hint: "A trader on an exchange’s trading floor executing orders in person." },
  { word: "Fallen Angel", hint: "A bond that was once investment grade but has been downgraded to non‑investment grade." },
  { word: "Gearing", hint: "A company’s level of debt relative to its equity/capital (leverage)." },
  { word: "Goodwill", hint: "Intangible asset arising when one company acquires another (above fair value)." },
  { word: "Growth Stock", hint: "A company expected to grow revenue/earnings above average; relevant for equity markets." },
  { word: "Gross Domestic", hint: "Total value of goods/services produced in a country; affects capital markets." },
  { word: "Green Bond", hint: "A bond issued to finance environmentally‑friendly or sustainable projects." },
  { word: "Global Depository", hint: "A negotiable certificate representing shares of a foreign company, traded locally." },
  { word: "Grey Market", hint: "Unofficial trading of securities before formal listing/issue." },
  { word: "Governance", hint: "System of rules & processes by which a company is directed/controlled; important for listed entities." },
  { word: "Gross Margin", hint: "A company’s revenue minus cost of goods sold; influences investor assessment in equity markets." },
  { word: "Good‑Till‑Cancelled", hint: "A trading order type that remains active until executed or cancelled." },
  { word: "Hedging", hint: "Strategy used to reduce or manage risk (often via derivatives)." },
  { word: "High‑Yield Bond", hint: "A bond with credit rating below investment grade, offering higher interest to compensate for risk." },
  { word: "Hard Currency", hint: "A currency that is widely accepted, stable and unlikely to depreciate significantly; relevant for cross‑border flows." },
  { word: "Hurdle Rate", hint: "Minimum rate of return an investment must achieve before profits/fees apply." },
  { word: "Holding Company", hint: "A business entity that owns enough voting stock in another company to control it." },
  { word: "Headline Inflation", hint: "Overall inflation rate including all items; important because inflation impacts interest rates and bond markets." },
  { word: "HFT", hint: "Algorithmic trading with very short holding periods, high turnover in securities markets." },
  { word: "Hard Capital Rationing", hint: "When a firm cannot raise external capital beyond a fixed budget constraint; influences issuance in capital markets." },
  { word: "Haircut", hint: "The difference between the market value of a security and the value ascribed to it for collateral or lending." },
  { word: "Head and Shoulder", hint: "A technical‑analysis formation in equity/trading markets signaling potential trend reversal." },
  
  
  {word: "Issuer Rating", hint: "Credit rating assigned to a company issuing securities"},
  {word: "IPO", hint: "Initial Public Offering  company goes public"},
  {word: "Index", hint: "A statistical measure of market performance"},
  {word: "Liquidity Adjustment", hint: "Modification to account for the ease of converting assets to cash"},
  {word: "Income Yield", hint: "Earnings from an investment as a percentage of its cost or market value"},
  {word: "Inflation-Linked", hint: "Bond where principal and interest adjust with inflation"},
  {word: "Insolvency Risk", hint: "Risk that a company cannot meet its financial obligations"},
  {word: "Institutional Funding", hint: "Investment capital provided by large organizations or institutions"},
  {word: "Interest Rate Swap", hint: "Contract exchanging fixed interest payments for floating ones"},
  {word: "IRR", hint: "Expected annualized return of an investment"},
  {word: "International Securities", hint: "Financial instruments traded across countries"},
  {word: "Investment Horizon", hint: "Time period an investor plans to hold an asset"},
  {word: "Investment Income", hint: "Returns earned from investments, such as dividends or interest"},
  {word: "Investment Strategy", hint: "Planned approach for allocating assets to meet objectives"},
  {word: "Issuer Obligation", hint: "Legal responsibility of a company issuing securities"},
  {word: "Issuer Compliance", hint: "Adherence by issuers to regulatory and disclosure requirements"},
  {word: "Job Creation Fund", hint: "Fund aimed at investing in projects that create employment"},
  {word: "Joint Liability", hint: "Shared financial responsibility among multiple parties"},
  {word: "Judgment Credit Risk", hint: "Risk of loss from a court ruling affecting financial assets"},
  {word: "Junior Bond", hint: "Bond with lower priority in repayment in case of default"},
  {word: "Key Account Risk", hint: "Risk of losing major clients or investors"},
  {word: "Key Rate Duration", hint: "Measure of bond sensitivity to interest rate changes"},
  {word: "Labor Cost Ratio", hint: "Proportion of total costs spent on labor"},
  {word: "Large Cap Stock", hint: "Stock of a company with high market capitalization"},
  {word: "Last Trading Day", hint: "Final day to trade a security before settlement or expiration"},
  {word: "Lead Arranger", hint: "Main bank coordinating a syndicated loan or deal"},
  {word: "Legal Risk", hint: "Risk of loss from lawsuits, non-compliance, or regulatory changes"},
  {word: "Lending Facility", hint: "Bank service providing funds to borrowers under agreed terms"},
  {word: "Lending Institution", hint: "Bank or financial firm providing loans"},
  {word: "Letter of Comfort", hint: "Non-binding assurance from a company or bank to a lender"},
  {word: "Leverage Effect", hint: "Impact of using debt to amplify investment returns"},
  {word: "Liquidity Coverage Ratio", hint: "Measure of a bank’s ability to cover short-term obligations"},
  {word: "Liquidity Ratio", hint: "Measures a firm's ability to meet short-term obligations"},
  {word: "Liquidity", hint: "Ease of converting assets into cash"},
  {word: "Liability", hint: "Financial obligation or debt"},
  {word: "Listed Derivative", hint: "Derivative instrument traded on a recognized exchange"},

  {word: "Matched Orders", hint: "When a buy order and a sell order meet at the same price" },
  {word: "Manipulation", hint: "Illegal interference with market prices or trading volume" },
  {word: "Margin Account", hint: "Brokerage account allowing purchase of securities with borrowed funds" },
  {word: "Margin Call", hint: "Demand for more funds when equity in a margin account falls below required level" },
  {word: "Market Abuse", hint: "Unlawful behavior like insider trading or price distortion" },
  {word: "Market Capitalization", hint: "Total value of a company's outstanding shares" },
  {word: "Market Infrastructure", hint: "Systems and institutions facilitating trading, clearing, and settlement" },
  {word: "Market Maker", hint: "Provides liquidity by quoting buy and sell prices for a security" },
  {word: "Market Manipulation", hint: "Deceptive practices to distort securities prices" },
  {word: "Market Order", hint: "An instruction to buy/sell immediately at the best available price" },
  {word: "Market Participant", hint: "Any entity involved in buying, selling, or advising on securities" },
  {word: "Market Risk", hint: "Risk of losses due to changes in market prices" },
  {word: "Market Share", hint: "The portion of an industry or market’s sales held by a company" },
  {word: "Market Surveillance", hint: "Monitoring trades to detect unfair or illegal practices" },
  {word: "Marking the Close", hint: "Trading at day’s end to influence closing price" },
  {word: "Material Fact", hint: "A fact that could affect an investor’s decision" },
  {word: "Material Information", hint: "Significant, non-public info that could influence investment decisions" },
  {word: "Mathematical Model", hint: "Quantitative method used for valuing or predicting security behavior" },
  {word: "Maturity Date", hint: "The date a bond or loan must be repaid in full" },
  {word: "Mutual Fund", hint: "Pooled investment vehicle managed by professionals" },
  {word: "Net Asset Value", hint: "Value of a fund’s assets minus liabilities, per share/unit" },
  {word: "Net Worth", hint: "Total assets minus total liabilities" },
  {word: "Nominal Value", hint: "Face value of a security, not its market price" },
  {word: "Nominee", hint: "Person or entity holding securities on behalf of the actual owner" },
  {word: "Non-Disclosure", hint: "Failure to reveal required material information" },
  {word: "Non-Public Information", hint: "Confidential data not yet available to general investors" },
  {word: "Order Execution", hint: "The completion of a buy or sell order in the market" },
  {word: "Offer Document", hint: "Official paper explaining a securities offering, often a prospectus" },
  {word: "Offering Price", hint: "Price at which a company sells its securities to the public" },
  {word: "Open Market", hint: "Market with free competition among buyers and sellers" },

  {word: "Option", hint: "Contract giving the right to buy or sell at a set price" },
  {word: "Order Book", hint: "Electronic list of buy/sell orders for a specific security" },
  {word: "Ordinary Share", hint: "Equity ownership in a company with voting rights" },
  {word: "Over-the-Counter", hint: "Trading done directly, not through a formal exchange" },
  {word: "Ownership Interest", hint: "Legal rights to part of a company or asset" },
  {word: "Par Value", hint: "Nominal or face value of a bond or share" },
  {word: "Participating Interest", hint: "Equity ownership in another company, usually with influence or control" },
  {word: "Payment Date", hint: "When interest, dividends, or capital is paid to investors" },
  {word: "Portfolio", hint: "Collection of financial assets held by an individual or institution" },
  {word: "Preference Share", hint: "A share that pays fixed dividends and has priority over common stock" },
  {word: "Preliminary Prospectus", hint: "Early version of a prospectus before final approval" },
  {word: "Price Discovery", hint: "Process of determining a security’s market price through supply and demand" },
  {word: "Price Manipulation", hint: "Illegal acts aimed at inflating or deflating a security’s price" },
  {word: "Primary Market", hint: "Market where new securities are sold to investors for the first time" },
  {word: "Primary Offering", hint: "The first sale of a company’s securities to the public" },
  {word: "Primary Regulator", hint: "Authority with main oversight of a regulated activity or entity" },
  {word: "Principal Amount", hint: "The original sum invested or borrowed, excluding interest" },
  {word: "Private Placement", hint: "Sale of securities to select investors without a public offer" },
  {word: "Prospectus", hint: "Document disclosing full details of a public securities offering" },
  {word: "Public Company", hint: "Share company offering securities to the public, with >50 shareholders" },
  {word: "Public Debt Security", hint: "Debt instrument issued by a government or public entity" },
  {word: "Public Enterprise", hint: "Government-owned and operated business entity" },
  {word: "Public Offer", hint: "Offering of securities to the general public, requiring approval" },
  {word: "Public Securities", hint: "Financial instruments offered to or traded by the public" },

  {word: "Quote", hint: "The current bid or ask price for a security"},
  {word: "Quantity", hint: "The number of shares or contracts in a trade"},
  {word: "Qualified", hint: "Meeting the legal requirements, as in an investor or offering"},

  {word: "Return", hint: "The gain or loss on an investment over a period"},
  {word: "Risk", hint: "The chance of an investment's value decreasing"},
  {word: "Rally", hint: "A period of sustained increases in market prices"},
  {word: "Rate", hint: "The level at which interest is charged or paid"},
  {word: "Ratio", hint: "A relationship between two financial numbers used for analysis"},
  {word: "Recession", hint: "A significant decline in economic activity"},
  {word: "Recovery", hint: "A period of rising after a decline in the market or economy"},
  {word: "Redemption", hint: "The repayment of a bond or mutual fund shares at maturity"},
  {word: "Register", hint: "An official list of security holders"},
  {word: "Regulator", hint: "A government body that oversees the market (e.g., ECMA)"},
  {word: "Report", hint: "A formal document of a company's financial performance"},
  {word: "Resistance", hint: "A price level a stock has difficulty rising above"},
  {word: "Revenue", hint: "The total income generated from business operations"},
  {word: "Rights", hint: "A privilege giving existing shareholders preemptive rights"},

  {word: "Stock", hint: "A share representing ownership in a corporation"},
  {word: "Share", hint: "A single unit of ownership in a company"},
  {word: "Sector", hint: "A category of companies in a similar industry"},
  {word: "Spread", hint: "The difference between the bid and ask price"},
  {word: "Settlement", hint: "The finalization of a trade where securities are delivered"},
  {word: "Securities", hint: "Tradable financial assets like stocks and bonds"},
  {word: "Short", hint: "Selling a borrowed asset hoping its price will fall"},
  {word: "Swap", hint: "A derivative contract to exchange cash flows or liabilities"},
  {word: "Strike", hint: "The set price at which an option can be exercised"},
  {word: "Supply", hint: "The total amount of a security available for purchase"},
  {word: "Surplus", hint: "An excess of revenue over expenditure"},
  {word: "Symbol", hint: "A unique series of letters representing a traded security"},
  {word: "Syndicate", hint: "A group of investment banks managing a security issuance"},
  {word: "Systemic", hint: "Risk of collapse of an entire financial system or market"},
  {word: "Savings", hint: "Money set aside for future use, not spent on consumption"},
  {word: "Scrip", hint: "A temporary document representing a fractional share"},
  {word: "Sector", hint: "A group of companies in similar industries"},
  {word: "Secured", hint: "A loan or bond backed by collateral"},
  {word: "Seller", hint: "The party in a transaction who is offering an asset"},
  {word: "Session", hint: "The period during which a market is open for trading"},
  {word: "Shares", hint: "Units of ownership interest in a corporation"},
  {word: "Stag", hint: "One who buys and sells newly issued shares for quick profit"},
  {word: "Stagnation", hint: "A period of little or no growth in the economy"},
  {word: "Stake", hint: "An ownership share or interest in a business"},
  {word: "Statement", hint: "A formal summary of an account or financial position"},
  {word: "Speculation", hint: "Taking high-risk positions hoping for high returns"},

  {word: "Trade", hint: "The action of buying or selling securities"},
  {word: "Turnover", hint: "The volume or frequency of trading in a market or portfolio"},
  {word: "Treasury", hint: "Relating to government debt, like U.S. Treasury bonds"},
  {word: "Tranche", hint: "A portion of a deal or security issue"},
  {word: "Trend", hint: "The general direction in which a market is moving"},
  {word: "Trigger", hint: "An event that causes an automatic action in a trade"},
  {word: "Trust", hint: "A fiduciary relationship where one party holds title for another"},
  {word: "Takeover", hint: "The acquisition of one company by another"},
  {word: "Tax", hint: "A compulsory financial charge imposed on income or profit"},
  {word: "Tenor", hint: "The time until a financial contract expires"},
  {word: "Term", hint: "The fixed period for which a loan or deposit is made"},
  {word: "Ticker", hint: "A symbol representing a particular stock on an exchange"},
  {word: "Tight", hint: "Describes a market with a narrow bid-ask spread"},
  {word: "Time", hint: "A key element in options (e.g., time value, time decay)"},
  {word: "Top", hint: "The highest price level a security or market reaches"},
  {word: "Total", hint: "The full or aggregate amount, as in total return"},
  {word: "Tracker", hint: "A fund that follows the performance of an index"},
  {word: "Trading", hint: "The act of buying and selling financial instruments"},
  {word: "Transfer", hint: "The movement of an asset from one owner to another"},
  {word: "Trough", hint: "The lowest point in an economic or market cycle"},
  {word: "Trustee", hint: "A person or firm that holds or manages property for another"},
  
  {word: "Underwriting", hint: "process of issuing new securities to investors"},
  {word: "upside", hint: "potential increase in value of an investment"},
  {word: "unsecured", hint: "type of debt not backed by collateral"},
  {word: "valuation", hint: "process of determining the value of an asset or company"},
  {word: "volume", hint: "number of shares"},
  {word: "venture", hint: "risky investment"},
  {word: "variance", hint: "statistical measure of spread in returns"},
  {word: "volatility", hint: "measure of price fluctuations in security or market"},
  {word: "vesting", hint: "gaining fill ownership of shares or options over time"},
  {word: "warrants", hint: "derivatives giving right to buy a company's stock"},
  {word: "writeoff", hint: "reduction in the value of asset"},
  {word: "withdrawal", hint: "taking money out of investment"},
  {word: "wealth", hint: "often a goal or measure in capital markets"},
  {word: "withholding", hint: "tax retained from income or dividends"},
  {word: "yield", hint: "income return from an investment"},
  {word: "zero coupon bond", hint: "sold at discount, no interest payment"},

];

